version: '3'
services:
  diegoforero:
    image: mantis/diegoforero
    volumes:
      - ../../:/app/
    ports:
      - "8000:8000"
    container_name: diegoforero
    restart: on-failure
    environment:
      - TERM=xterm
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_DIEGOFORERO=${DB_DIEGOFORERO}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - DB_HOST=${DB_HOST}
    depends_on:
      - diegoforero-postgresql
    networks:
      - mantis
  diegoforero-postgresql:
    image: postgres:11.6
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DB_DIEGOFORERO}
    container_name: diegoforero-postgresql
    networks:
      milenanet:
        aliases:
          - diegoforero-postgresql
    volumes:
      - ../../.data/diegoforero-postgres:/var/lib/postgresql/data
networks:
   milenanet:
     external: true
