# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='img',
            field=models.ImageField(upload_to=home.models.portfolio_item_image, verbose_name='Portada'),
        ),
    ]
