# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160121_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='order',
            field=models.SmallIntegerField(default=1, verbose_name='orden'),
            preserve_default=False,
        ),
    ]
